In [1]:
import pandas as pd
import numpy as np

In [15]:
final = pd.read_csv('C:/Users/chenyuzhou/Desktop/final.csv')

In [29]:
final

user_id  order_times  order_spend  review_comment  form_comment  \
0        86499            2         16.0               0             0   
1        86500            3         30.0               0             0   
2        86501            2         16.0               0             0   
3        86502            2         16.0               0             0   
4        86503            2         16.0               0             0   
...        ...          ...          ...             ...           ...   
47051   133830            1        239.5               0             0   
47052   133834            1         32.0               0             0   
47053   133836            3         51.0               0             0   
47054   133837            2         30.5               0             0   
47055   133838            3         54.0               0             0   

       total_comment  sub_times  cancelled  LOGIN  VIEW_PRODUCT  \
0                  0          0          0      0             0   
1                  0          0          0      0             0   
2                  0          0          0      2             0   
3                  0          0          0      0             0   
4                  0          0          0      0             0   
...              ...        ...        ...    ...           ...   
47051              0          0          0      0             0   
47052              0          0          0      0             0   
47053              0          0          0      0             0   
47054              0          0          0      0             0   
47055              0          0          0      0             0   

       ADD_ITEM_TO_CART  POINTS_ADDED  view_per_login  item_per_view  \
0                     0             0             0.0            0.0   
1                     0             0             0.0            0.0   
2                     0             0             0.0            0.0   
3                     0             0             0.0            0.0   
4                     0             0             0.0            0.0   
...                 ...           ...             ...            ...   
47051                 0             0             0.0            0.0   
47052                 0             0             0.0            0.0   
47053                 0             0             0.0            0.0   
47054                 0             0             0.0            0.0   
47055                 0             0             0.0            0.0   

       points_per_add  
0                 0.0  
1                 0.0  
2                 0.0  
3                 0.0  
4                 0.0  
...               ...  
47051             0.0  
47052             0.0  
47053             0.0  
47054             0.0  
47055             0.0  

[47056 rows x 15 columns]

In [33]:
final.columns

Index(['user_id', 'order_times', 'order_spend', 'review_comment',
       'form_comment', 'total_comment', 'sub_times', 'cancelled', 'LOGIN',
       'VIEW_PRODUCT', 'ADD_ITEM_TO_CART', 'POINTS_ADDED', 'view_per_login',
       'item_per_view', 'points_per_add'],
      dtype='object')

In [34]:
select=final[['user_id','order_times','order_spend','total_comment','sub_times', 'cancelled','view_per_login','item_per_view', 'points_per_add']]

In [149]:
select

user_id  order_times  order_spend  total_comment  sub_times  cancelled  \
0        86499            2         16.0              0          0          0   
1        86500            3         30.0              0          0          0   
2        86501            2         16.0              0          0          0   
3        86502            2         16.0              0          0          0   
4        86503            2         16.0              0          0          0   
...        ...          ...          ...            ...        ...        ...   
47051   133830            1        239.5              0          0          0   
47052   133834            1         32.0              0          0          0   
47053   133836            3         51.0              0          0          0   
47054   133837            2         30.5              0          0          0   
47055   133838            3         54.0              0          0          0   

       view_per_login  item_per_view  points_per_add  
0                 0.0            0.0             0.0  
1                 0.0            0.0             0.0  
2                 0.0            0.0             0.0  
3                 0.0            0.0             0.0  
4                 0.0            0.0             0.0  
...               ...            ...             ...  
47051             0.0            0.0             0.0  
47052             0.0            0.0             0.0  
47053             0.0            0.0             0.0  
47054             0.0            0.0             0.0  
47055             0.0            0.0             0.0  

[47056 rows x 9 columns]

In [36]:
select.columns

Index(['user_id', 'order_times', 'order_spend', 'total_comment', 'sub_times',
       'cancelled', 'view_per_login', 'item_per_view', 'points_per_add'],
      dtype='object')

In [314]:
list=['order_times', 'order_spend', 'total_comment', 'sub_times','cancelled', 'view_per_login', 'item_per_view', 'points_per_add']

In [315]:
list

['order_times',
 'order_spend',
 'total_comment',
 'sub_times',
 'cancelled',
 'view_per_login',
 'item_per_view',
 'points_per_add']

In [316]:
values=[]
for i in list:
    a=select[i].sort_values(ascending=True)
    a=a.tolist()
    q_20=a[9410]
    q_50=a[23527]
    q_80=a[37644]
    q_95=a[44702]
    q=[q_20,q_50,q_80,q_95]
    values.append(q)

In [317]:
index=[]
for i in list:
    s = select[['user_id',i]]
    rounds = 0
    for j in range(4):
        d = s[s[i]==values[rounds][j]]
        dd = d['user_id'].values
        rounds = rounds+1
        index.append(dd)

In [318]:
values

[[0, 2, 5, 25],
 [0.0, 28.0, 103.71, 428.0],
 [0, 0, 1, 2],
 [0, 0, 1, 3],
 [0, 0, 1, 2],
 [0.0, 1.208333333, 5.529411765, 14.0],
 [0.0, 0.3125, 0.538461538, 1.333333333],
 [0.0, 0.0, 0.5, 2.285714286]]

In [319]:
index

[array([ 87237,  88821,  92040, ..., 133770, 133771, 133774], dtype=int64),
 array([ 86594,  88216,  88385,  88401,  88647,  90866,  91699,  91809,
         91947,  91960,  92526,  92624,  92931,  93271,  93761,  94988,
         95763,  95830,  95888,  97412,  97551,  97711,  97790,  97866,
         98320,  98418,  98463,  98928,  99241,  99619,  99621,  99672,
         99757, 100323, 100340, 100522, 101190, 101786, 101811, 101813,
        102421, 103892, 103910, 104242, 105605, 106277, 108487, 109338,
        110391, 110573, 111762, 113724, 113945, 114343, 116014, 116856,
        117535, 119578, 120563, 120951, 121353, 121408, 121868, 122070,
        122301, 122907, 124090, 125254, 126366, 126584, 126842, 126981,
        127432, 128244, 128263, 131442, 132060], dtype=int64),
 array([ 86568,  86601,  86672, ..., 133826, 133830, 133834], dtype=int64),
 array([ 86500,  86505,  86508, ..., 133825, 133836, 133838], dtype=int64),
 array([ 87237,  87521,  87768, ..., 133771, 133774, 133778],

In [320]:
n = len(index)
inter = 4 # 间隔
index_20= index[0:n:inter]
index_50= index[1:n:inter]
index_80= index[2:n:inter]
index_95= index[3:n:inter]


In [321]:
index_20

[array([ 87237,  88821,  92040, ..., 133770, 133771, 133774], dtype=int64),
 array([ 87237,  87521,  87768, ..., 133771, 133774, 133778], dtype=int64),
 array([ 86499,  86500,  86501, ..., 133836, 133837, 133838], dtype=int64),
 array([ 86499,  86500,  86501, ..., 133836, 133837, 133838], dtype=int64),
 array([ 86499,  86500,  86501, ..., 133836, 133837, 133838], dtype=int64),
 array([ 86499,  86500,  86501, ..., 133836, 133837, 133838], dtype=int64),
 array([ 86499,  86500,  86501, ..., 133836, 133837, 133838], dtype=int64),
 array([ 86499,  86500,  86501, ..., 133836, 133837, 133838], dtype=int64)]

In [322]:
def extend(a):
    a[0]=a[0].tolist()
    for i in range(1,8):
        a[i]=a[i].tolist()
        a[0].extend(a[i])
    return a[0]

In [323]:
extend_20=extend(index_20)

In [324]:
extend_50=extend(index_50)

In [325]:
extend_80=extend(index_80)

In [326]:
extend_95=extend(index_95)

In [327]:
len(extend_20),len(extend_50),len(extend_80),len(extend_95)

(199674, 852, 38910, 9327)

In [328]:
pd20 = pd.value_counts(extend_20)

In [329]:
pd20[pd20==8].index

Int64Index([ 87237, 116397, 116436, 116435, 116430, 116427, 116422, 116414,
            116402, 116395,
            ...
            106980, 104552, 105627, 106546, 107946, 104841, 104572, 105500,
             99225, 104834],
           dtype='int64', length=3118)

In [371]:
pd50 = pd.value_counts(extend_50)

In [372]:
pd50

120398    3
127521    2
111712    2
86594     1
102990    1
         ..
97400     1
97472     1
97522     1
97547     1
127713    1
Length: 848, dtype: int64

In [331]:
pd50[pd50==3].index

Int64Index([120398], dtype='int64')

In [332]:
pd80 = pd.value_counts(extend_80)

In [333]:
pd80[pd80==6].index

Int64Index([ 93190, 104978, 103705, 129313, 102749, 129259, 117966, 104917,
            125437,  90018,
            ...
            124319, 116483, 132198, 104657, 103436, 100510, 122238, 100512,
            104291, 106168],
           dtype='int64', length=160)

In [334]:
pd95 = pd.value_counts(extend_95)

In [335]:
pd95[pd95==4].index

Int64Index([ 98711, 131414, 127178, 116495, 110413, 112810, 110162, 121528,
            121344,  97506, 114205, 130326, 131171, 114163, 124093, 109445,
            112491, 117849, 109149,  86878,  98382, 121183],
           dtype='int64')

In [336]:
pd95=pd95[pd95==4].index.tolist()

In [337]:
pd80=pd80[pd80==6].index.tolist()

In [338]:
pd50=pd50[pd50==3].index.tolist()

In [339]:
pd20=pd20[pd20==8].index.tolist()

In [349]:
std_final = pd.read_csv('C:/Users/chenyuzhou/Desktop/std_final.csv')

In [350]:
std_select=std_final[['user_id','order_times','order_spend','total_comment','sub_times', 'cancelled','view_per_login','item_per_view', 'points_per_add']]

In [352]:
user95 = std_select[std_select['user_id'].isin(pd95)]

In [353]:
user80 = std_select[std_select['user_id'].isin(pd80)]

In [369]:
user50 = std_select[std_select['user_id'].isin(pd50)]

In [355]:
user20 = std_select[std_select['user_id'].isin(pd20)]

In [379]:
std_select.describe()

user_id   order_times   order_spend  total_comment     sub_times  \
count   47057.000000  4.705700e+04  4.705700e+04   4.705700e+04  4.705700e+04   
mean   110184.055826  4.831878e-17  9.180568e-17  -4.831878e-18 -4.227893e-17   
std     13668.354661  1.000000e+00  1.000000e+00   1.000000e+00  1.000000e+00   
min         1.000000 -3.436685e-01 -3.711873e-01  -2.484237e-01 -2.711104e-01   
25%     98334.000000 -3.436685e-01 -3.639154e-01  -2.484237e-01 -2.711104e-01   
50%    110227.000000 -2.213053e-01 -2.621085e-01  -2.484237e-01 -2.711104e-01   
75%    122008.000000 -9.894212e-02 -7.303865e-02  -2.484237e-01  2.223963e-01   
max    133838.000000  3.697710e+01  3.524667e+01   8.483805e+01  8.313154e+01   

          cancelled  view_per_login  item_per_view  points_per_add  
count  4.705700e+04    4.705700e+04   4.705700e+04    4.705700e+04  
mean   1.932751e-17   -3.865502e-17   1.932751e-17    8.697380e-17  
std    1.000000e+00    1.000000e+00   1.000000e+00    1.000000e+00  
min   -2.411820e-01   -6.160629e-01  -6.961862e-01   -1.727890e-01  
25%   -2.411820e-01   -6.160629e-01  -6.961862e-01   -1.727890e-01  
50%   -2.411820e-01   -3.962980e-01  -1.547855e-01   -1.727890e-01  
75%   -2.411820e-01    1.720597e-01   1.700549e-01   -9.052197e-02  
max    8.515846e+01    2.251837e+01   3.222098e+01    5.264264e+01

In [380]:
std_select.mean()

user_id           1.101841e+05
order_times       4.831878e-17
order_spend       9.180568e-17
total_comment    -4.831878e-18
sub_times        -4.227893e-17
cancelled         1.932751e-17
view_per_login   -3.865502e-17
item_per_view     1.932751e-17
points_per_add    8.697380e-17
dtype: float64

In [377]:
user20.mean()

user_id           117422.906350
order_times           -0.343668
order_spend           -0.363915
total_comment         -0.248424
sub_times             -0.271110
cancelled             -0.241182
view_per_login        -0.616063
item_per_view         -0.696186
points_per_add        -0.172789
dtype: float64

In [378]:
user20.describe()

user_id   order_times   order_spend  total_comment   sub_times  \
count    3118.000000  3.118000e+03  3.118000e+03   3.118000e+03  3118.00000   
mean   117422.906350 -3.436685e-01 -3.639154e-01  -2.484237e-01    -0.27111   
std      8579.560733  5.552006e-17  1.110401e-16   2.776003e-17     0.00000   
min     87237.000000 -3.436685e-01 -3.639154e-01  -2.484237e-01    -0.27111   
25%    109762.000000 -3.436685e-01 -3.639154e-01  -2.484237e-01    -0.27111   
50%    117449.500000 -3.436685e-01 -3.639154e-01  -2.484237e-01    -0.27111   
75%    124420.500000 -3.436685e-01 -3.639154e-01  -2.484237e-01    -0.27111   
max    133754.000000 -3.436685e-01 -3.639154e-01  -2.484237e-01    -0.27111   

          cancelled  view_per_login  item_per_view  points_per_add  
count  3.118000e+03    3.118000e+03    3118.000000    3.118000e+03  
mean  -2.411820e-01   -6.160629e-01      -0.696186   -1.727890e-01  
std    2.776003e-17    1.110401e-16       0.000000    5.552006e-17  
min   -2.411820e-01   -6.160629e-01      -0.696186   -1.727890e-01  
25%   -2.411820e-01   -6.160629e-01      -0.696186   -1.727890e-01  
50%   -2.411820e-01   -6.160629e-01      -0.696186   -1.727890e-01  
75%   -2.411820e-01   -6.160629e-01      -0.696186   -1.727890e-01  
max   -2.411820e-01   -6.160629e-01      -0.696186   -1.727890e-01

In [370]:
user50.mean()

user_id           120398.000000
order_times            2.042414
order_spend            2.001494
total_comment         13.848743
sub_times             13.547080
cancelled             14.339245
view_per_login         0.126591
item_per_view          0.046306
points_per_add        -0.108151
dtype: float64

In [367]:
user80.mean()

user_id           108690.568750
order_times           -0.091677
order_spend           -0.181437
total_comment          0.255047
sub_times              0.222396
cancelled              0.279548
view_per_login        -0.434188
item_per_view          1.036296
points_per_add         0.074012
dtype: float64

In [368]:
user95.mean()

user_id           114404.363636
order_times            0.329329
order_spend            0.293157
total_comment          1.261987
sub_times              1.209410
cancelled              1.321007
view_per_login        -0.086602
item_per_view          0.102569
points_per_add         0.190869
dtype: float64

In [388]:
user20.mean().values

array([ 1.17422906e+05, -3.43668500e-01, -3.63915411e-01, -2.48423735e-01,
       -2.71110438e-01, -2.41181982e-01, -6.16062921e-01, -6.96186227e-01,
       -1.72788988e-01])

In [391]:
std_select.mean().values

array([ 1.10184056e+05,  4.83187784e-17,  9.18056789e-17, -4.83187784e-18,
       -4.22789311e-17,  1.93275114e-17, -3.86550227e-17,  1.93275114e-17,
        8.69738011e-17])

In [393]:
user80.mean().values

array([ 1.08690569e+05, -9.16768062e-02, -1.81437056e-01,  2.55046514e-01,
        2.22396346e-01,  2.79547568e-01, -4.34188463e-01,  1.03629599e+00,
        7.40120788e-02])

In [395]:
user95.mean().values

array([ 1.14404364e+05,  3.29329043e-01,  2.93157013e-01,  1.26198701e+00,
        1.20940991e+00,  1.32100667e+00, -8.66017900e-02,  1.02568777e-01,
        1.90868644e-01])

In [398]:
a=[-3.43668500e-01, -3.63915411e-01, -2.48423735e-01,-2.71110438e-01, -2.41181982e-01, -6.16062921e-01, -6.96186227e-01,-1.72788988e-01]

In [400]:
b=[4.83187784e-17,  9.18056789e-17, -4.83187784e-18,-4.22789311e-17,  1.93275114e-17, -3.86550227e-17,  1.93275114e-17,8.69738011e-17]

In [402]:
c=[-9.16768062e-02, -1.81437056e-01,  2.55046514e-01,2.22396346e-01,  2.79547568e-01, -4.34188463e-01,  1.03629599e+00,7.40120788e-02]

In [403]:
d=[3.29329043e-01,  2.93157013e-01,  1.26198701e+00,1.20940991e+00,  1.32100667e+00, -8.66017900e-02,  1.02568777e-01,1.90868644e-01]

In [412]:
dataset=np.array(std_select.iloc[:,1:])

In [415]:
import random
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 计算欧拉距离
def calcDis(dataSet, centroids, k):
    clalist=[]
    for data in dataSet:
        diff = np.tile(data, (k, 1)) - centroids  #相减   (np.tile(a,(2,1))就是把a先沿x轴复制1倍，即没有复制，仍然是 [0,1,2]。 再把结果沿y方向复制2倍得到array([[0,1,2],[0,1,2]]))
        squaredDiff = diff ** 2     #平方
        squaredDist = np.sum(squaredDiff, axis=1)   #和  (axis=1表示行)
        distance = squaredDist ** 0.5  #开根号
        clalist.append(distance) 
    clalist = np.array(clalist)  #返回一个每个点到质点的距离len(dateSet)*k的数组
    return clalist

# 计算质心
def classify(dataSet, centroids, k):
    # 计算样本到质心的距离
    clalist = calcDis(dataSet, centroids, k)
    # 分组并计算新的质心
    minDistIndices = np.argmin(clalist, axis=1)    #axis=1 表示求出每行的最小值的下标
    newCentroids = pd.DataFrame(dataSet).groupby(minDistIndices).mean() #DataFramte(dataSet)对DataSet分组，groupby(min)按照min进行统计分类，mean()对分类结果求均值
    newCentroids = newCentroids.values
 
    # 计算变化量
    changed = newCentroids - centroids
 
    return changed, newCentroids

# 使用k-means分类
def kmeans(dataSet, k):
    # 随机取质心
    centroids=[a,b,c,d]
    # 更新质心 直到变化量全为0
    changed, newCentroids = classify(dataSet, centroids, k)
    while np.any(changed != 0):
        changed, newCentroids = classify(dataSet, newCentroids, k)
 
    centroids = sorted(newCentroids.tolist())   #tolist()将矩阵转换成列表 sorted()排序
 
    # 根据质心计算每个集群
    cluster = []
    clalist = calcDis(dataSet, centroids, k) #调用欧拉距离
    minDistIndices = np.argmin(clalist, axis=1)  
    for i in range(k):
        cluster.append([])
    for i, j in enumerate(minDistIndices):   #enymerate()可同时遍历索引和遍历元素
        cluster[j].append(dataSet[i])
        
    return centroids, cluster
 



In [416]:
centroids, cluster = kmeans(dataset, 4)
print('质心为：%s' % centroids)
print('集群为：%s' % cluster)

质心为：[[-0.23332878424309234, -0.13257458681174716, -0.038799741907569046, -0.0560459529539227, -0.0303462577712977, 2.1437665196729294, -0.08050987005859854, -0.13041816170328005], [-0.18822531520839164, -0.2283878160714294, -0.0884776889991497, -0.09669582650841384, -0.08065823924179145, -0.3933434891980242, 1.8600240410256175, 0.0011252283272263522], [-0.10137692218809266, -0.10575475394340664, -0.09400228312515094, -0.09525334170416015, -0.09400495525081638, -0.26196100939021183, -0.3336658897075926, -0.0748504708771753], [3.8502233705080844, 3.752740056731339, 2.5922327649684966, 2.7145570001908954, 2.530685686634136, -0.17301184327420038, 0.2091520605633518, 2.1278704938569097]]


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [420]:
len(cluster[0]),len(cluster[1]),len(cluster[2]),len(cluster[3])

(5404, 6157, 33973, 1523)

In [421]:
dataset

array([[-0.22130531, -0.30574006, -0.24842374, ..., -0.61606292,
        -0.69618623, -0.17278899],
       [-0.16012372, -0.25483663, -0.24842374, ..., -0.61606292,
        -0.69618623, -0.17278899],
       [-0.22130531, -0.30574006, -0.24842374, ..., -0.61606292,
        -0.69618623, -0.17278899],
       ...,
       [-0.22130531, -0.25301865, -0.24842374, ..., -0.61606292,
        -0.69618623, -0.17278899],
       [-0.16012372, -0.1675736 , -0.24842374, ..., -0.61606292,
        -0.69618623, -0.17278899],
       [-0.3436685 , -0.36391541,  8.3105705 , ..., -0.61606292,
        -0.69618623, -0.17278899]])

In [386]:
dataset = createDataSet()
random.sample(dataset, 3)

[[2, 1], [1, 1], [1, 2]]

In [ ]:
random.sample(dataSet, k)